export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SUCCESSFUL = "SUCCESSFUL";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
export const RIGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const IS_REGISTERING = "IS_REGISTERING";
